### ISSUE TITLE
Error while trying to test the model

### ISSUE THREAD

**Issue by sahanHe** [shuozh/resLF#9]
Hi. Thank you for uploading the code. when i tried to run the model using the stanford dataset following error occurs.

Traceback (most recent call last):
  File "resLF-master/resLF_test.py", line 348, in <module>
    gpu_no=gpu_no)
  File "resLF-master/resLF_test.py", line 108, in main
    gt_ycbcr, lr_ycbcr = image_input(image_path + image_name, scale, view_n, view_n_ori, interpolation)
  File "<path to my files>/resLF-master\func_input.py", line 49, in image_input
    j + num_vew_gap::view_num_ori, :]
ValueError: could not broadcast input array from shape (583,841,3) into shape (582,840,3)

can anyone please help me

**Comment by shuozh** [comment]
Please check if the original angular resolution is set as 14 for the stanford dataset.

**Comment by sahanHe** [comment]
Yes, It works. Thank you for your time.
